export {
  BACKEND_CANISTER_ID_LOCAL_FALLBACK,
  CYCLES_LEDGER_CANISTER_ID_LOCAL,
  DFX_NETWORK,
  IDENTITY_PROVIDER_URL_LOCAL,
  II_CANISTER_ID_LOCAL,
  LEAGER_ICP_ID_LOCAL,
  SIGNER_CANISTER_ID_LOCAL,
} from "../icp/runtime";
